### ISSUE TITLE
Problem running run.sh

### ISSUE THREAD

**Issue by vnunez89** [pLesur/PoistonTapContainer#1]
When I run the script it says, line 9: Docker: command not found. Do I need to install something else to get this script to build and start?

**Comment by lesurp** [comment]
Oh I should have been more specific in my README.
To use this container you need to install Docker, a tool that allows you to run "containers". This is close to a Virtual Machine (but not exactly the same). If you want to learn more about it, you should check [Docker's website](https://www.docker.com/).

Depending on which system you want to run the Nodejs server on, it might not be worth getting into Docker just for that (although learning Docker is valuable in general), although you should honestly be able to install Docker and run my container without even understanding Docker at all.

If your system already uses a Nodejs version that supports the PoisonTap code (ECMAScript v6), you really don't have to bother with this container - just start PoisonTap `node backend_server.js`.
If, like me, you run Debian, for which the package Nodejs does not support ECMAScript v6, then using a container is definitely easier.

Hope that helped !

**Comment by vnunez89** [comment]
Okay I see thanks for the explanation, it makes more sense now. I am using Rasbian Jessie to run the nodejs server on I finally got it up and running with the backend_server.js you provided in your download actually, the other one that came with poison tap kept giving me errors.

**Comment by vnunez89** [comment]
By the way i was also wondering if you could help me out with one more thing, So Ive installed and set up PoisonTap, ive plugged it into a victims computer(my desktop) i let it do its thing, I unplugged it, hooked it back up to my keyboard and screen, then i started the backend server, then after that I'm sort of confused on what to do. Ive read up on how to use nodejs and done quite a few tutorials, but i guess  I'm just stuck on how to use PoisonTap correctly. how do i visit the websites of the cookies i took? like what do you do ?
